// components/mla-dashboard/grievance-management/table/grievances-table.tsx
"use client"

import { DataTable } from "./data-table"
import { columns, type Grievance } from "./columns"
import { useThemeStore } from "@/store/useThemeStore"

const data: Grievance[] = [
  {
    sl: 1,
    id: "GRV-2024-001",
    citizenName: "Rajesh Kumar Patra",
    citizenId: "CIT-2024-045",
    phone: "+91 9438991122",
    category: "Water Supply",
    subject: "No water supply for 3 days in Ward 5",
    location: "Badakotha",
    assignedDept: "Water Resources",
    status: "In Progress",
    assignedTo: "Santosh Behera",
    registrationDate: "2024-12-20",
    lastUpdated: "2024-12-25",
  },
  {
    sl: 2,
    id: "GRV-2024-002",
    citizenName: "Sarita Nayak",
    citizenId: "CIT-2024-023",
    phone: "+91 9437889900",
    category: "Road Repair",
    subject: "Potholes on main road causing accidents",
    location: "Korei Market",
    assignedDept: "Public Works",
    status: "Forwarded",
    assignedTo: "Prakash Jena",
    registrationDate: "2024-12-22",
    lastUpdated: "2024-12-24",
  },
  {
    sl: 3,
    id: "GRV-2024-003",
    citizenName: "Biswajit Sahoo",
    citizenId: "CIT-2024-067",
    phone: "+91 9438776655",
    category: "Electricity",
    subject: "Frequent power cuts affecting businesses",
    location: "Nuagaon",
    assignedDept: "Electricity",
    status: "Pending",
    assignedTo: "Anita Mishra",
    registrationDate: "2024-12-23",
    lastUpdated: "2024-12-23",
  },
  {
    sl: 4,
    id: "GRV-2024-004",
    citizenName: "Manjulata Swain",
    citizenId: "CIT-2024-089",
    phone: "+91 9437665544",
    category: "Sanitation",
    subject: "Garbage not collected for a week",
    location: "Hatapada",
    assignedDept: "Sanitation",
    status: "Resolved",
    assignedTo: "Ramesh Das",
    registrationDate: "2024-12-15",
    lastUpdated: "2024-12-21",
  },
  {
    sl: 5,
    id: "GRV-2024-005",
    citizenName: "Pradeep Mohanty",
    citizenId: "CIT-2024-112",
    phone: "+91 9438554433",
    category: "Street Light",
    subject: "Street lights not working in colony area",
    location: "Jharbandh",
    assignedDept: "Public Works",
    status: "In Progress",
    assignedTo: "Sujata Panda",
    registrationDate: "2024-12-18",
    lastUpdated: "2024-12-24",
  },
  {
    sl: 6,
    id: "GRV-2024-006",
    citizenName: "Sunita Barik",
    citizenId: "CIT-2024-134",
    phone: "+91 9437443322",
    category: "Health",
    subject: "PHC lacks basic medicines and staff",
    location: "Bansapal",
    assignedDept: "Health & Family Welfare",
    status: "Forwarded",
    assignedTo: "Dr. Amit Tripathy",
    registrationDate: "2024-12-21",
    lastUpdated: "2024-12-25",
  },
  {
    sl: 7,
    id: "GRV-2024-007",
    citizenName: "Ashok Parida",
    citizenId: "CIT-2024-156",
    phone: "+91 9438332211",
    category: "Education",
    subject: "School building in dilapidated condition",
    location: "Telkoi",
    assignedDept: "Education",
    status: "Pending",
    assignedTo: "Lipika Mohapatra",
    registrationDate: "2024-12-24",
    lastUpdated: "2024-12-24",
  },
  {
    sl: 8,
    id: "GRV-2024-008",
    citizenName: "Mamata Rout",
    citizenId: "CIT-2024-178",
    phone: "+91 9437221100",
    category: "Pension",
    subject: "Widow pension not received for 2 months",
    location: "Ghasipura",
    assignedDept: "Social Welfare",
    status: "In Progress",
    assignedTo: "Bijay Dash",
    registrationDate: "2024-12-19",
    lastUpdated: "2024-12-26",
  },
  {
    sl: 9,
    id: "GRV-2024-009",
    citizenName: "Santosh Behera",
    citizenId: "CIT-2024-201",
    phone: "+91 9438110099",
    category: "Water Supply",
    subject: "Water quality issue - contaminated supply",
    location: "Badakotha",
    assignedDept: "Water Resources",
    status: "Forwarded",
    assignedTo: "Prakash Jena",
    registrationDate: "2024-12-22",
    lastUpdated: "2024-12-25",
  },
  {
  sl: 10,
  id: "GRV-2024-010",
  citizenName: "Prakash Jena",
  citizenId: "CIT-2024-223",
  phone: "+91 9437009988",
  category: "Road Repair",
  subject: "Drainage overflow during rain",
  location: "Korei Market",
  assignedDept: "-",
  status: "Resolved",
  assignedTo: "Santosh Behera",
  registrationDate: "2024-12-16",
  lastUpdated: "2024-12-20",
},
]

export function GrievancesTable() {
  const { theme } = useThemeStore()

  return (
    <div 
      className="w-full rounded-lg border shadow-lg p-6"
      style={{
        background: theme.cardBackground,
        borderColor: theme.border,
      }}
    >
      <DataTable columns={columns} data={data} />
    </div>
  )
}